coverage:
    status:
      project:
        default: false
        service: 
          target: auto
          threshold: 1%
          base: auto
          only_pulls: false
          paths: "src"
          branches: 
            - '**'
      comment:
        layout: "reach, diff, flags, files"
        behavior: default
        require_changes: false  # if true: only post the comment if coverage changes
        require_base: no        # [yes :: must have a base report to post]
        require_head: no
        branches: 
          - '**