version: '3'
services:
  hip-infi:
    build: .
    ports:
      - "9053:80"
    depends_on:
      - db-infi
      - otp-infi
      - rabbitmq-infi
  otp-infi:
    build: src/In.ProjectEKA.OtpService/.
    depends_on:
      - db-infi
  db-infi:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=welcome
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  rabbitmq-infi:
    image: "rabbitmq:3"
    ports:
      - "5672:5672"
volumes:
  postgresql:
  postgresql_data: