version: '3'
services:
  hip:
    build: .
    ports:
      - "9052:80"
    depends_on:
      - db
      - rabbitmq
      - otp
  otp:
    build: src/In.ProjectEKA.OtpService/.
    depends_on:
      - db
  gateway:
    build: gatewayStubConfigurations/.
    ports:
      - "2525:2525"
      - "8000:8000"
  oidc-server-mock:
    image: soluto/oidc-server-mock
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          }
        }
      API_SCOPES_INLINE: |
        [
          "some-app-scope-1"
        ]
      API_RESOURCES_INLINE: |
        [
          {
            "Name": "some-app",
            "Scopes": ["some-app-scope-1"]
          }
        ]
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1",
            "Username":"User1",
            "Password":"pwd"
          }
        ]
      CLIENTS_CONFIGURATION_PATH: /gatewayStubConfigurations/oicdConfigs/clients-config.json
    volumes:
      - ./gatewayStubConfigurations/oicdConfigs/clients-config.json:/gatewayStubConfigurations/oicdConfigs/clients-config.json
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=welcome
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  rabbitmq:
    image: "rabbitmq:3"
    ports:
      - "5672:5672"
  filebeat:
    container_name: filebeat
    build:
      context: .
      dockerfile: filebeat.Dockerfile
    volumes:
      - ./logs:/var/log
    networks:
      - elk
  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

volumes:
  postgresql:
  postgresql_data:
    
networks:
  elk:
    external: true